In [1]:
import torch
import numpy as np
import torch.nn as nn


In [30]:
a = torch.FloatTensor([
    [
        1.,2.,3.
    ],
    [
        4.,5.,6.
    ]
],)

In [31]:
a.dtype

torch.float32

In [32]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [33]:
aa = torch.stack([a,a])

In [34]:
aa

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

In [35]:
aa.shape

torch.Size([2, 2, 3])

In [40]:
n = nn.Dropout1d(0.5)
m = nn.Dropout(0.2)

In [41]:
n(aa)

tensor([[[ 2.5000,  5.0000,  7.5000],
         [10.0000, 12.5000, 15.0000]],

        [[ 2.5000,  5.0000,  7.5000],
         [ 0.0000,  0.0000,  0.0000]]])

In [42]:
aa.shape

torch.Size([2, 2, 3])

In [45]:
aa[1].shape

torch.Size([2, 3])

In [47]:
m(aa)

tensor([[[0.0000, 3.1250, 4.6875],
         [6.2500, 7.8125, 9.3750]],

        [[1.5625, 3.1250, 0.0000],
         [0.0000, 7.8125, 9.3750]]])

In [52]:
import random
c = [torch.tensor([1,1,1]),
     torch.tensor([1,1,0]),
     torch.tensor([1,0,1]),
     torch.tensor([0,1,1]),
     torch.tensor([1,0,0]),
     torch.tensor([0,1,0]),
     torch.tensor([0,0,1])]

c = torch.stack([torch.tensor([1,1,1]),
     torch.tensor([1,1,0]),
     torch.tensor([1,0,1]),
     torch.tensor([0,1,1]),]).to(device='cuda')
random.choice(c)

tensor([0, 1, 1], device='cuda:0')